### ISSUE TITLE
Changed `service` for Playbulb

### ISSUE THREAD

**Issue by tomayac** [BluetoothRocks/Lightbulb#1]
The new Playbulbs seem to have changed and now instead of `0xff0f` require `0xff02` as in this configuration:

```js
/* Playbulb */
    {
      filters: [{ namePrefix: "PLAYBULB" }],
      optionalServices: [0xff02], // 👈🆕

      write: {
        service: 0xff02,  // 👈🆕
        characteristic: 0xfffc,
        format: function(r, g, b) {
          return new Uint8Array([0x00, r, g, b]);
        }
      },

      read: {
        service: 0xff02,  // 👈🆕
        characteristic: 0xfffc,
        interpret: function(buffer) {
          return {
            r: buffer.getUint8(1),
            g: buffer.getUint8(2),
            b: buffer.getUint8(3)
          };
        }
      }
    },
```

**Comment by NielsLeenheer** [comment]
I also have Playbulb with the service `0xff00`. So we have three different devices with three different services in use. And we need to include all of the variants in the list of supported lightbulbs. 

And then find a way to figure out which to use when we connect to the device. I did something similar for the Matrix example using `getPrimaryServices()`, so it should not be that difficult. I'll look into it.

**Comment by tomayac** [comment]
Thanks a lot! Appreciate the effort!

**Comment by NielsLeenheer** [comment]
Can you try again?

With commit 9e2854f I've added support for multiple types of Playbulb. It basically fetches a list of bulb definitions based on namePrefix and then one by one try to access the services specified in optionalServices. If the services are not there, next definition is tried. If the services are there, we've found the right bulb definition. 

It now works for the two types of Playbulb that I have. I've also added the definition for the `0xff02` type.

**Comment by NielsLeenheer** [comment]
Oh, latest commit is active on https://bluetooth.rocks

**Comment by tomayac** [comment]
Thank you very much, this worked like a charm in the end! Really annoying that they introduce such breaking changes… Thanks for the fix again!
